services:
  auth:
    build: .
    ports:
      - "5000:5000"
    develop:
      watch:
        - action : rebuild
          path : ./package.json

        - action : sync+restart
          path : .
          target : /usr/src/app
          exec : 
            command : npm run start


        
        
